version: "3.9"
services:

  example-spring-security-database:
    image: postgres:15.6
    container_name: example-spring-security
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
